// launcher/src/shell/Navigation.tsx
import { Link, useLocation } from "react-router-dom"
import { Gamepad2 } from "lucide-react"
import { channelManager } from "../lib/channels"
import { useStore } from "../lib/store"
import { getProfile } from "../lib/api"
import { Badge } from "../components/Badge"
import styles from "./Navigation.module.css"

export function Navigation() {
	useStore(channelManager)

	const avatarLetter = (getProfile().username?.[0] ?? "?").toUpperCase()
	const runningCount = Object.values(channelManager.channels).filter((c) => !c.stopped).length
	const onRunning = useLocation().pathname.startsWith("/running")

	return (
		<nav className={styles.nav}>
			<Link to="/scripts" className={styles.brand} aria-label="Navigate to home page">
				Elixer Scripts
			</Link>

			<div className={styles.actions}>
				{runningCount > 0 || onRunning ? (
					<Link
						to={onRunning ? "/scripts" : "/running"}
						className={styles.running}
						data-active={onRunning ? "" : undefined}
						aria-label="Show running scripts"
					>
						<Gamepad2 size={18} />
						Running
						{runningCount > 0 && <Badge color="primary" round>{runningCount}</Badge>}
					</Link>
				) : (
					<span className={styles.runningDisabled} title="No scripts running">
						<Gamepad2 size={18} />
						Running
					</span>
				)}

				<Link to="/settings" className={styles.avatarLink} aria-label="Open settings">
					<span className={styles.avatar}>{avatarLetter}</span>
				</Link>
			</div>
		</nav>
	)
}

// launcher/src/routes/(app)/Navigation.svelte
<script lang="ts">
	import { page } from "$app/state"
	import { Avatar } from "@skeletonlabs/skeleton-svelte"
	import Gamepad2 from "@lucide/svelte/icons/gamepad-2"
	import { channelManager } from "$lib/communication.svelte"

	const { profile } = $derived(page.data)

	const avatarLetter = $derived((profile?.username?.[0] ?? "?").toUpperCase())

	const runningCount = $derived(
		Object.values(channelManager.channels).filter((c) => !c.stopped).length
	)

	const onRunning = $derived(page.url.pathname.startsWith("/running"))
</script>

<nav class="w-full flex-col text-base">
	<div
		class="flex h-full w-full justify-between bg-surface-300/30 font-semibold backdrop-blur-md dark:bg-surface-800/30"
	>
		<a
			href="/scripts"
			class="mx-4 my-auto flex h-full items-center text-lg font-bold tracking-wide text-surface-600 hover:text-primary-800 dark:text-primary-500 dark:hover:text-primary-100"
			aria-label="Navigate to home page"
			data-sveltekit-preload-data="false"
		>
			Elixer Scripts
		</a>

		<div class="mx-2 flex items-center gap-2">
			{#if runningCount > 0 || onRunning}
				<a
					href={onRunning ? "/scripts" : "/running"}
					class="btn flex h-10 items-center gap-2 {onRunning
						? 'preset-filled-primary-500'
						: 'hover:preset-tonal'}"
					aria-label="Show running scripts"
					data-sveltekit-preload-data="false"
				>
					<Gamepad2 size={18} />
					Running
					{#if runningCount > 0}
						<span class="badge rounded-full preset-filled-primary-500 px-2">{runningCount}</span>
					{/if}
				</a>
			{:else}
				<span
					class="btn flex h-10 cursor-default items-center gap-2 opacity-40"
					title="No scripts running"
				>
					<Gamepad2 size={18} />
					Running
				</span>
			{/if}

			<a
				href="/settings"
				class="group flex items-center"
				aria-label="Open settings"
				data-sveltekit-preload-data="false"
			>
				<Avatar
					class="h-10 w-10 rounded-full border-2 border-surface-500 group-hover:border-primary-500"
				>
					<Avatar.Fallback class="text-lg font-bold">{avatarLetter}</Avatar.Fallback>
				</Avatar>
			</a>
		</div>
	</div>
</nav>
